Add support for RXE backend device
Signed-off-by: Yuval Shaia <yuval.shaia@oracle.com>

diff --git a/qemu/configure_pvrdma b/qemu/configure_pvrdma
--- a/qemu/configure_pvrdma
+++ b/qemu/configure_pvrdma
@@ -1,4 +1,4 @@
-#/bin/bash
+#!/bin/bash
 
 create_macvtap()
 {
@@ -20,10 +20,17 @@ mng_eth=$1
 eth=$2
 num_vms=$3
 
+ifconfig ${mng_eth} > /dev/null 2>&1
+if [ $? -ne 0 ];
+then
+	echo "Can't find interface ${mng_eth}"
+	exit 2
+fi
+
 ifconfig ${eth} > /dev/null 2>&1
 if [ $? -ne 0 ];
 then
-	echo "Can't find interface $1"
+	echo "Can't find interface ${eth}"
 	exit 2
 fi
 
@@ -37,6 +44,12 @@ do
 	f=$(echo ${ipv6} | awk -F: '{print $1}')
 	f=$((0x${f} + ${i}))
 	f=$(printf "%x\n" ${f})
+	# Special case where IP start with 0, let's pad it with 5
+	if [ $(echo $f|wc -c) -eq 4 ];
+	then
+		f="5$f"
+	fi
+
 	ifconfig ${eth} add $(echo ${ipv6} | awk -F: -v v1=${f} '{print "fe80::"v1":"$2":"$3":"$4}')
 done
 
@@ -60,9 +73,9 @@ modprobe ib_core; modprobe ib_umad; modprobe rdma_ucm; modprobe ib_uverbs;
 # If not Mellanox RoCE device then let's start rxe
 if [ $(ethtool -i ${eth}|grep driver|grep mlx|wc -l) -eq 0 ]
 then
-	echo "rxe net_dev=${eth}"
+	#echo "rxe net_dev=${eth}"
 	modprobe rdma_rxe;
 	echo ${eth} > /sys/module/rdma_rxe/parameters/add
-	echo "rxe gid table"
-	cat /sys/class/infiniband/rxe0/ports/1/gids/[0-4]
+	#echo "rxe gid table"
+	#cat /sys/class/infiniband/rxe0/ports/1/gids/[0-4]
 fi
diff --git a/qemu/start_vm b/qemu/start_vm
--- a/qemu/start_vm
+++ b/qemu/start_vm
@@ -16,6 +16,20 @@ then
 	exit 1
 fi
 
+mng_eth=$1
+eth=$2
+idx=$3
+
+vm_name="${eth}-${idx}"
+log=/tmp/qemu_${eth}_${idx}.log
+vm_img_file=pvrdma-${eth}-${idx}.qcow2
+
+ifconfig ${mng_eth} > /dev/null 2>&1
+if [ $? -ne 0 ];
+then
+	echo "Can't find interface ${mng_eth}"
+	exit 2
+fi
 ifconfig ${eth} > /dev/null 2>&1
 if [ $? -ne 0 ];
 then
@@ -23,38 +37,29 @@ then
 	exit 2
 fi
 
-mng_eth=$1
-eth=$2
-idx=$3
-
-name="${eth}-${idx}"
-
-log=/tmp/qemu_${eth}_${idx}.log
-
-vm_img_file=pvrdma-${eth}-${idx}.qcow2
-if [ ! -f ${images_dir}/${vm_img_file} ];
+backend_dev=$(ls /sys/class/net/${eth}/device/infiniband 2>/dev/null)
+# Lets see first that RXE is configured
+if [ $? != 0 ];
 then
-	cd ${images_dir}
-	qemu-img create -f qcow2 -o backing_file=${base_image} ${vm_img_file}
-	cd -
+	echo "Please run configure_pvrdma first"
+	exit 3
 fi
 
-ipv6=$(ifconfig ${eth}|grep inet6|grep -n fe80|grep ^${idx}|awk '{print $3}')
-
-s=$(echo ${ipv6}|awk -F:: '{print $2}')
-s=$(echo ${s}|awk -F: '{print $1}')
-backend_dev=$(ls /sys/class/net/${eth}/device/infiniband)
-fn=$(grep -l1 ${s} /sys/class/net/${eth}/device/infiniband/${backend_dev}/ports/1/gids/*)
-# We take the odd entry since it supports RoCE v2
-backend_gid_idx=$(basename $(grep -l1 ${s} /sys/class/net/${eth}/device/infiniband/${backend_dev}/ports/1/gids/*|tail -1))
-
-# If this is RXE setup thhen start from gid 3
+# If this is RXE setup then start from gid 3
+#is_roce=$(ls /sys/class/net/${eth}/device/|grep infiniband|wc -l)
 if [ $(ethtool -i ${eth}|grep driver|grep mlx|wc -l) -eq 0 ];
 then
-	macvtap_idx=$((${idx} - 2))
+	macvtap_idx=$((${idx} + 2))
 else
 	macvtap_idx=${idx} 
 fi
+
+ipv6=$(ifconfig ${eth}|grep inet6|grep -n fe80|grep ^${idx}|awk '{print $3}')
+s=$(echo ${ipv6}|awk -F:: '{print $2}')
+s=$(echo ${s}|awk -F: '{print $1}')
+fn=$(grep -l1 ${s} /sys/class/net/${eth}/device/infiniband/${backend_dev}/ports/1/gids/*)
+# We take the odd entry since it supports RoCE v2
+backend_gid_idx=$(basename $(grep -l1 ${s} /sys/class/net/${eth}/device/infiniband/${backend_dev}/ports/1/gids/*|tail -1))
 
 backend_port=1
 pci_addr_roce=10
@@ -63,7 +68,6 @@ pci_addr_local=11
 uniq_id=$((0x$(sha1sum <<<${eth}${idx}|cut -c1-2)))
 vnc=${vnc_ip}:${uniq_id}
 tcp_port=$((10000 + ${uniq_id}))
-#tcp_port=1002${idx}
 
 pvrdma_args="-device pvrdma,addr=${pci_addr_roce}.1,backend-dev=${backend_dev},backend-gid-idx=${backend_gid_idx},backend-port=${backend_port}"
 
@@ -83,7 +87,14 @@ eth_for_pvrdma="-netdev user,id=id0,hostfwd=tcp::${tcp_port}-:22 -device vmxnet3
 
 eth_for_macvtap="-netdev tap,id=tap0,fd=3 3<>/dev/tap$(cat /sys/class/net/${eth}_${macvtap_idx}/ifindex) -device e1000,addr=${pci_addr_local},mac=${macvtap_mac},netdev=tap0"
 
-cmd="$qemu -name ${name} ${snapshot} -display vnc=${vnc} -object memory-backend-ram,id=mb1,size=${mem},share -numa node,memdev=mb1 -m ${mem} -smp ${cpus} --enable-kvm -hda ${images_dir}/${vm_img_file} ${hdb} ${pvrdma_args} ${eth_for_pvrdma} ${eth_for_macvtap} >${log} &"
+if [ ! -f ${images_dir}/${vm_img_file} ];
+then
+	cd ${images_dir}
+	qemu-img create -f qcow2 -o backing_file=${base_image} ${vm_img_file}
+	cd -
+fi
+
+cmd="$qemu -name ${vm_name} ${snapshot} -display vnc=${vnc} -object memory-backend-ram,id=mb1,size=${mem},share -numa node,memdev=mb1 -m ${mem} -smp ${cpus} --enable-kvm -hda ${images_dir}/${vm_img_file} ${hdb} ${pvrdma_args} ${eth_for_pvrdma} ${eth_for_macvtap} >${log} &"
 
 rm -f /tmp/exec.$$
 echo ${cmd} > /tmp/exec.$$
